---

- name: Playbook du TP n°03 pour le backend
  hosts: backend
  tasks:
    - name: Installation de PostgreSQL
      become: true
      ansible.builtin.package:
        name: postgresql
        state: present

- name: Playbook du TP n°03 pour le frontend
  hosts: frontend
  tasks:
    - name: Création d'un utilisateur
      become: true
      ansible.builtin.user:
        name: "{{ nom_utilisateur }}"
        password: "{{ mot_de_passe_utilisateur }}"

    - name: Copie d'un fichier statique dans le répertoire home de l'utilisateur
      # Comme on va copier le fichier dans le répertoire d'un autre utilisateur, on a besoin d'une escalade de privilèges ici aussi
      become: true
      ansible.builtin.copy:
        # Comme on utilise le module 'copy', Ansible ira chercher tout seul le fichier indiqué dans le répertoire 'files'
        src: fichier_statique
        # On va réutiliser la variable 'nom_utilisateur' pour trouver le répertoire home de l'utilisateur fraîchement créé
        # Notez que la variable étant au milieu de la chaîne de caractères, on a pas besoin de l'entourer de guillemets cette fois-ci
        dest: /home/{{ nom_utilisateur }}/fichier_statique

    - name: Download and unpack latest WordPress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"

    - name: Copie d'un fichier dynamique
      ansible.builtin.template:
        src: fichier_dynamique
        dest: "{{ }}"
        owner: x
        group: x
        mode: x
