---

- name: Actions communes aux deux machines
  tasks:
    - name: Création d'un utilisateur dédié
      become: true
      ansible.builtin.user:
        name: "{{ nom_utilisateur }}"
        password: "{{ mot_de_passe_utilisateur }}"

- name: Actions sur la machine backend
  hosts: backend
  tasks:
    - name: Installation de PostgreSQL
      become: true
      ansible.builtin.package:
        name: postgresql
        state: present

- name: Actions sur la machine frontend
  hosts: frontend
  tasks:
    - name: Téléchargement et décompression de WordPress
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"

    - name: Récupération des salts WordPress
      ansible.builtin.uri:
        url: https://api.wordpress.org/secret-key/1.1/salt/
      register: wordpress_salts

    - name: Affichage des salts WordPress
      ansible.builtin.debug:
        var: wordpress_salts

    - name: Copie du fichier de configuration
      ansible.builtin.template:
        # Comme on est dans le module 'template', Ansible va aller chercher le fichier dans le répertoire 'templates'
        # Les templates étant des fichiers Jinja2, il est possible d'omettre l'extension '.j2' lorsqu'on référence le fichier
        # TODO: j'ai un doute, à vérifier
        src: wp-config.php
        dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
        owner: "{{ nom_utilisateur }}"
        group: "{{ nom_utilisateur }}"
        mode: '0600'

    # https://kaiten.design/how-to-automate-wordpress-and-wp-config-php-creation/
